@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model
Model -> Model : setPredicate(PREDICATE_SHOW_ALL_PERSONS)
[<-- Model
deactivate Model

[-> Model : getFilteredPersonList()
activate Model
[<--Model : FilteredList<Person>
deactivate Model

[-> Model : sortListByDate(BY_DATE_THEN_SLOT)
activate Model

Model -> Model : setComparator(BY_DATE_THEN_SLOT)
[<-- Model
deactivate Model
@enduml