@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Class HiddenOutside #FFFFFF

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

package "Schedule Storage" #F4F6F6 {
Class "<<interface>>\nScheduleStorage" as ScheduleStorage
Class JsonScheduleStorage
Class JsonSerializableSchedule
Class JsonAdaptedActivity
}

HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -right-> "1" UserPrefsStorage
StorageManager -right-> "1" AddressBookStorage
StorageManager -left-> "1" ScheduleStorage

Storage -left-|> UserPrefsStorage
Storage -left-|> AddressBookStorage
Storage -right-|> ScheduleStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonScheduleStorage .up.|> ScheduleStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag
JsonScheduleStorage ..> JsonSerializableSchedule
JsonSerializableSchedule --> "*" JsonAdaptedActivity

@enduml
